src/TestApp3/Controllers/AdminController.cs
using Microsoft.AspNet.Authorization;
using Microsoft.AspNet.Hosting;
using Microsoft.AspNet.Http;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Mvc;
using Microsoft.Net.Http.Headers;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Blogness.Models;
using Blogness.Models.Admin;
using Blogness.Models.Blog;
using Blogness.Models.Repository.Interfaces;

namespace Blogness.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private readonly SignInManager<User> _signInManager;
        private readonly UserManager<User> _userManager;
        private readonly IRepository<Post> _postRepository;
        private readonly IHostingEnvironment _hostingEnvironment;

        public AdminController (
            UserManager<User> userManager, 
            SignInManager<User> signInManager, 
            IRepository<Post> postRepository, 
            IHostingEnvironment hostingEnvironment)
        {
            _signInManager = signInManager;
            _userManager = userManager;
            _postRepository = postRepository;
            _hostingEnvironment = hostingEnvironment;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult WritePost()
        {
            var model = new PostViewModel { Id = MongoDB.Bson.ObjectId.GenerateNewId().ToString() };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> WritePost(PostViewModel model)
        {
            if (ModelState.IsValid)
            {
                var post = new Post() { Id = model.Id, Title = model.Title, Content = model.Body, Tags = model.Tags, UserName = User.Identity.Name };
                await _postRepository.InsertAsync(post);
            }
            else
            {
                return View(model);
            }

            return RedirectToAction(nameof(BlogController.Index), nameof(BlogController).ControllerName());
        }

        [HttpGet]
        public async Task<IActionResult> EditPost(string id)
        {
            var model = new BlogViewModel();

            if (string.IsNullOrEmpty(id))
            {
                var posts = await _postRepository.GetResults();
                model.RecentPosts = posts.OrderByDescending(o => o.DatePublished).ToList();
                return View("EditPostList", model);
            }
            else
            {
                var postToEdit = await _postRepository.GetResults(p => p.Id == id, 1);
                var post = postToEdit.First();

                if (post == null)
                {
                    return RedirectToAction(nameof(AdminController.Index));
                }

                model.Body = post.Content;
                model.Title = post.Title;
                model.Id = post.Id;
                model.Tags = post.Tags;

                var filePath = GetFilePath(id);

                model.Images = Directory.Exists(filePath) 
                    ? Directory.GetFiles(filePath)
                        .Select(path => path.Substring(path.IndexOf("\\img\\"), path.Length - path.IndexOf("\\img\\")))
                        .ToArray() 
                    : new string[0];
               
                return View(model);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPost(BlogViewModel model)
        {
            if (ModelState.IsValid)
            {
                var postToEdit = await _postRepository.GetResults(p => p.Id == model.Id, 1);
                var post = postToEdit.First();

                post.Title = model.Title;
                post.Content = model.Body;
                post.Tags = model.Tags;
                post.DateUpdated = DateTime.Now;

                await _postRepository.UpdateAsync(post);
            }
            else
            {
                return View(model);
            }

            return RedirectToAction(nameof(BlogController.Index), nameof(BlogController).ControllerName());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upload(IFormFile file)
        {
            var id = Request.Form["id"];

            var fileName = ContentDispositionHeaderValue.Parse(file.ContentDisposition).FileName.Trim('"');
            var filePath = GetFilePath(id);

            if (fileName.IsImage())
            {
                Directory.CreateDirectory(filePath);

                var savePath = Path.Combine(filePath, fileName);
                await file.SaveAsAsync(savePath);
            }
            return Json(new { FileName = fileName, FilePath = filePath, Success = true });
        }

        [HttpGet]
        public async Task<IActionResult> Comments()
        {
            var postsWithComments = await _postRepository.GetResults(p => p.Comments != null);
            var model = new List<UnapprovedCommentModel>();

            foreach (var post in postsWithComments)
            {
                foreach (var comment in post.Comments)
                {
                    if (!comment.Approved)
                    {
                        model.Add(new UnapprovedCommentModel { Comment = comment, Post = post });
                    }
                }
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Comments(IEnumerable<UnapprovedCommentModel> model)
        {

            foreach (var unapprovedComment in model)
            {
                if (unapprovedComment.Post != null && unapprovedComment.Post.Id != null)
                {
                    var postResults = await _postRepository.GetResults(p => p.Id == unapprovedComment.Post.Id, 1);
                    var postToUpdate = postResults.FirstOrDefault();

                    var comment = postToUpdate?.Comments?.FirstOrDefault(c => c?.Id == unapprovedComment?.Comment?.Id);
                    if (comment != null)
                    {
                        if (unapprovedComment.Approved)
                        {
                            comment.Approved = true;
                        }
                        else
                        {
                            postToUpdate.Comments.Remove(comment);
                        }
                    }
                    await _postRepository.UpdateAsync(postToUpdate);
                }
                else
                {
                    return View(model);
                }
            }       
            return RedirectToAction(nameof(AdminController.Index), nameof(AdminController).ControllerName());
        }

        private string GetFilePath(string id)
        {
            return Path.Combine(_hostingEnvironment.WebRootPath, string.Format("img\\{0}\\", id));
        }
    }
}

src/TestApp3/Controllers/BlogController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Blogness.Models;
using Blogness.Models.Admin;
using Blogness.Models.Blog;
using Blogness.Models.Repository.Interfaces;

namespace Blogness.Controllers
{
    public class BlogController : Controller
    {
        private readonly IRepository<Post> _postRepository;
        private readonly UserManager<User> _userManager;

        public BlogController(IRepository<Post> postRepository, UserManager<User> userManager)
        {
            _postRepository = postRepository;
            _userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var posts = await _postRepository.GetResults();
            foreach (var post in posts)
            {
                await post.SetUser(_userManager);
            }
            var model = new BlogViewModel()
            {
                RecentPosts = posts.OrderByDescending(o => o.DatePublished).ToList()
            };
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> ViewPost(string id)
        {
            var posts = await _postRepository.GetResults(p => p.Id == id);
            var post = posts.FirstOrDefault();

            if (post != null)
            {
                await post.SetUser(_userManager);
                return View(post);
            }
            return RedirectToAction(nameof(BlogController.Index));

        }

        [HttpGet]
        public async Task<IActionResult> Tagged(string tag)
        {
            var posts = await _postRepository.GetResults(p => p.Tags.Contains(tag));
            foreach (var post in posts)
            {
                await post.SetUser(_userManager);
            }
            var model = new BlogViewModel()
            {
                RecentPosts = posts.OrderByDescending(o => o.DatePublished).ToList()
            };
            return View(nameof(BlogController.Index), model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LeaveComment(Comment model)
        {
            model.DateCreated = DateTime.Now;

            var posts = await _postRepository.GetResults(p => p.Id == model.PostId);
            var post = posts.FirstOrDefault();

            //This is so a user posting a comment can see the comment on the site immediately. In reality, site admin will have to approve the comment before it's publicly visible
            var existingUnapprovedComments = Request.Cookies["commentId"];
            if (!string.IsNullOrWhiteSpace(existingUnapprovedComments))
            {
                Response.Cookies.Append("commentId", string.Join("Z", existingUnapprovedComments, model.Id));
            }
            else
            {
                Response.Cookies.Append("commentId", model.Id);
            }

            if (post != null)
            {
                if (post.Comments != null)
                {
                    post.Comments.Add(model);
                }
                else
                {
                    post.Comments = new List<Comment> { model };
                }
            }
            await _postRepository.UpdateAsync(post);

            return RedirectToAction(nameof(BlogController.ViewPost), new { id = model.PostId });
        }
    }
}

src/TestApp3/Views/Shared/_AdminPartial.cshtml
<div class="col-md-2 sidebar sidebar-left sidebar-md-show sidebar-animate">
    <ul class="nav nav-stacked">
        <li><a asp-controller="Admin" asp-action="WritePost">Write a Post</a></li>
        <li><a asp-controller="Admin" asp-action="EditPost">Edit a Post</a></li>
        <li><a asp-controller="Admin" asp-action="Comments">Review Comments</a></li>
        <li><a asp-controller="Account" asp-action="Manage">Manage Your Account</a></li>
        <li><a asp-controller="Admin" asp-action="Manage">Manage the Site</a></li>
        <li><a asp-controller="Admin" asp-action="Stats">View Site Stats</a></li>
    </ul>
</div>

src/TestApp3/Views/Shared/_CommentPartial.cshtml
@model Comment

<div class="panel panel-default col-md-10">
    <div class="panel-body col-md-1">
        <img src="http://www.gravatar.com/avatar/@Model.HashEmail()?d=retro" class="img-rounded" />
    </div>
    <div class="panel-body col-md-8">
        <p><h4><a href="@Model.Website">@Model.Author</a><span class="comment-date">@Model.DateCreated</span></h4></p>
        <p>@Model.Content</p>
    </div>
</div>

src/TestApp3/Views/Shared/_FileUploadPartial.cshtml
<div id="image-upload-btn" class="btn btn-default" onclick="getFile()" style="margin-bottom:15px;">Upload image</div>
<div style="height:0px;width:0px;overflow:hidden;">
    <input type="file" name="file" id="image-upload"/>
</div>
<div class="container">
    <div class="row" id="uploaded-images">
        @if (Model.Images != null)
        {
            @foreach (var image in Model.Images)
            {
                <img src="@image" class="img-thumbnail col-md-1" style="margin-left:5px;margin-right:5px;" />
            }
        }
    </div>
</div>

src/TestApp3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" type="text/css" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="~/lib/bootstrap/css/bootstrap-theme.min.css" />
    <link rel="stylesheet" type="text/css" href="~/lib/bootstrap-sidebar/css/sidebar.css" />
    <link rel="stylesheet" type="text/css" href="~/css/site.css" /> <!--Change to .min for release-->
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-controller="Home" asp-action="Index" class="navbar-brand">Minimum Viable Product</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Blog" asp-action="Index">blog</a></li>
                </ul>
                @if (User.Identity.IsAuthenticated)
                {
                    <form asp-controller="Account" asp-action="LogOut" method="post" id="logoutForm" class="navbar-right">
                        <ul class="nav navbar-nav navbar-right">
                            <li><a asp-controller="Admin" asp-action="Index">Welcome, @User.Identity.Name.ToLower()</a></li>
                            <li><a href="javascript:document.getElementById('logoutForm').submit()">Log Out</a></li>
                        </ul>
                    </form>
                }         
            </div>
        </div>
    </div>
    <div class="container-fluid body-content">
        @RenderBody()
    </div>
    <script src="~/lib/jquery/js/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/lib/bootstrap-sidebar/js/sidebar.js"></script>
    <script src="~/js/site.js"></script><!--Change to .min for release-->
</body>
</html>

src/TestApp3/Views/Shared/_LeaveCommentPartial.cshtml
@model Comment

<div class="panel panel-default col-md-10">
    <form class="col-md-10 form-horizontal" asp-action="LeaveComment" asp-controller="Blog" method="post" role="form">
        <div class="form-group" style="padding-top:20px;">
            <label asp-for="Author" class="col-md-1 control-label"></label>
            <div class="col-md-6">
                <input asp-for="Author" class="form-control" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Email" class="col-md-1 control-label"></label>
            <div class="col-md-6">
                <input asp-for="Email" class="form-control" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Website" class="col-md-1 control-label"></label>
            <div class="col-md-6">
                <input asp-for="Website" class="form-control" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Content" class="col-md-1 control-label"></label>
            <div class="col-md-6">
                <textarea asp-for="Content" class="form-control" rows="6"></textarea>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-7">
                <button type="submit" class="btn btn-default pull-right">Post Comment</button>
            </div>
        </div>
        <input type="hidden" value="@Model.PostId" name="PostId" id="PostId" />
    </form>
</div> 